Pool: Azure Pipelines
Image: vs2017-win2016
Queued: Just now [manage parallel jobs]
Agent: Azure Pipelines 2
Started: Just now
Duration: 34s

The agent request is already running or has already completed.
Job preparation parameters
Job live console data:
S# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: vs2017-win2016

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
